name: Run thetvapp.py

on:
  schedule:
    - cron: '1 12/12 * * *'  #'0 7/24 * * *'  # 每天早上7点，每24小时运行一次
  workflow_dispatch:

jobs:
  run-scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Run thetvapp.py
      run: |
        cd $GITHUB_WORKSPACE/thetvapp
        python thetvapp.py

    - name: process playlist.txt
      run: |
        cd $GITHUB_WORKSPACE/thetvapp
        sed -i '1i thetvapp,#genre#' thetvapplist.txt
        sed -i 's|-| |g' thetvapplist.txt
        sed -i 's| live stream||g' thetvapplist.txt
        bash ../rtp2m3u.sh "thetvapplist.txt"
        
    - name: bark
      run: |
        cd $GITHUB_WORKSPACE
        msg="$(TZ='Asia/Shanghai' date +%Y/%m/%d/%H:%M:%S)
        thetvappLIst updated."
        msg_urlencode=$(bash ./url_process/encode.sh "$msg")
        curl "https://api.day.app/X7a24UtJyBYFHt5Fma7jpP/github_actions/${msg_urlencode}?isArchive=1"
        
    - name: Stage changes
      run: |
        echo "Staging changes..."
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git stash
        git pull --rebase origin main
        git stash pop
        git add .
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update thetvapp.list"
        branch: main  # Commit to the main branch
