name: thetvapp token sniffer

on:
  schedule:
    - cron: '0 8-23/2 * * *'  # 每天早上8点到晚上23点，每2个小时运行一次
  workflow_dispatch:

jobs:
  run-scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Run thetvapp.py and update thetvapplist.txt
      run: |
        cd $GITHUB_WORKSPACE/thetvapp
        token=$(python tokenSniffer.py | ggrep -oP 'value:\s\K.*')
        sed -i 's|token=.*$|token="${token}"|g' thetvapplist.txt
        sed -i '1i thetvapp,#genre#' thetvapplist.txt
        bash ../speedtest/rtp2m3u.sh "thetvapplist.txt"

    - name: Stage changes
      run: |
        echo "Staging changes..."
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update token in thetvapplist.txt"
        branch: main  # Commit to the main branch
